# Generated by Django 5.1.4 on 2024-12-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_category_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
