# Generated by Django 5.1.4 on 2024-12-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_order_complete_order_transaction_id_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
