# Generated by Django 5.1.4 on 2024-12-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_order_complete_remove_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Dress', 'Dress')], max_length=20, null=True),
        ),
    ]
