# Generated by Django 5.1.4 on 2025-01-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phoneno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
