# Generated by Django 5.1.4 on 2025-01-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_shippingaddress_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phoneno',
        ),
    ]
