# Generated by Django 5.1.4 on 2025-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_shippingaddress_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phoneno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
