# Generated by Django 5.1.4 on 2025-01-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_shippingaddress_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
