# Generated by Django 5.1.4 on 2025-01-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=20),
        ),
    ]
