# Generated by Django 5.1.4 on 2025-01-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
