# Generated by Django 5.1.4 on 2025-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_profile_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
