# Generated by Django 5.1.4 on 2025-01-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_product_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offer_price',
            new_name='fake_price',
        ),
    ]
